apiVersion: apps/v1
kind: Deployment
metadata:
  name: kissankonnect-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kissankonnect-web
  template:
    metadata:
      labels:
        app: kissankonnect-web
    spec:
      containers:
        - name: kissankonnect-web
          image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/2401152/kissankonnect:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "root"
            - name: DB_NAME
              value: "kissankonnect"
---
apiVersion: v1
kind: Service
metadata:
  name: kissankonnect-service
spec:
  type: NodePort
  selector:
    app: kissankonnect-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
